name: Sonarr

services:
  sonarr:
    image: ghcr.io/hotio/sonarr:release-${SONARR_VERSION}
    container_name: sonarr
    volumes:
      - sonar_config:/config:rw
      - ~/Videos/series:/series:rw
      - ~/Downloads:/data/downloads:rw
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '127.0.0.1:8989:8989'
    networks:
      - backend
    restart: unless-stopped
    labels:
      - wud.tag.include=^release-\d+\.\d+\.\d+.\d+$$
      - traefik.enable=true
      - traefik.http.routers.sonarr-sonarr.rule=Host(`sonarr.dhjensen.tech`)

networks:
  backend:
    external: true
    driver: bridge

volumes:
  sonar_config:
